name: dreamark
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.6.2=py38h06a4308_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.4=hbda6634_3
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - pytorch=1.13.0=py3.8_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.13.0=py38_cu117
  - torchvision=0.14.0=py38_cu117
  - typing_extensions=4.11.0=py38h06a4308_0
  - urllib3=2.2.2=py38h06a4308_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.1.0
      - accelerate==0.31.0
      - aiofiles==24.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - augly==1.0.0
      - beautifulsoup4==4.12.3
      - cachetools==5.3.3
      - carvekit-colab==4.1.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clip==1.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - dearpygui==1.11.1
      - debugpy-run==1.8
      - diffusers==0.15.0
      - dnspython==2.6.1
      - einops==0.8.0
      - email-validator==2.2.0
      - exceptiongroup==1.2.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - filelock==3.15.4
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - ftfy==6.2.0
      - gdown==5.2.0
      - google-auth==2.30.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.64.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - imageio==2.34.2
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.0
      - iopath==0.1.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - kornia==0.7.3
      - kornia-rs==0.1.4
      - lightning-utilities==0.11.3.post0
      - loguru==0.7.2
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.1
      - ninja==1.11.1.1
      - numpy==1.24.4
      - nvdiffrast==0.3.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - orjson==3.10.5
      - packaging==24.1
      - pandas==2.0.3
      - pillow==10.4.0
      - portalocker==2.10.1
      - protobuf==5.27.2
      - psutil==6.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pygments==2.18.0
      - pymcubes==0.1.4
      - pymeshlab==2023.12.post1
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-magic==0.4.27
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rsa==4.9
      - safetensors==0.4.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentence-transformers==3.0.1
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - starlette==0.37.2
      - sympy==1.12.1
      - taming-transformers-rom1504==0.0.6
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - timm==1.0.7
      - tokenizers==0.19.1
      - torch-ema==0.3
      - torchmetrics==1.4.0.post0
      - tqdm==4.66.4
      - transformers==4.42.3
      - trimesh==4.4.1
      - triton==2.3.1
      - typer==0.12.3
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - ujson==5.10.0
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.0.3
      - xatlas==0.0.9
      - yarl==1.9.4
      - zipp==3.19.2
